# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cca824d7e2b6a048e5cf8428a419a7778dbfe40d7c43e4c8bfa6f2d3d593db3ca508d9cf3900b22bf07e672279db795b5a70b136774bddc961e6a3d348a761c

test:
  secret_key_base: 66833f7ed5d2211c9729a07272bfcf661b7181eca9112776a15bd0e6eea1d1975d25d80aad2c7569e6bb51389ab5decdc359682e6237c8bfd22567a4c627839a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
